name: bip32_keys
description: A BIP32 with SLIP132 support for Dart/Flutter community.
version: 3.1.0
homepage: https://github.com/ethicnology/dart-bip32-keys

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  pointycastle: ^3.9.1
  bs58check: ^1.0.2
  hex: ^0.2.0

dev_dependencies:
  test: ^1.26.2
  lints: ^5.1.1
